# Generated by Django 2.1.1 on 2018-09-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_work_site', '0002_auto_20180928_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='referense',
            field=models.CharField(default='/404/', max_length=250),
        ),
    ]
