# Generated by Django 2.1.1 on 2018-09-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_work_site', '0003_product_referense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='referense',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=250),
        ),
    ]
