# Generated by Django 2.1.1 on 2018-09-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_work_site', '0004_auto_20180928_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='referense',
        ),
    ]
